# Generated by Django 3.1.3 on 2021-02-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumptions', '0003_auto_20210202_1032'),
        ('consumptions', '0003_auto_20210202_1136'),
    ]

    operations = [
    ]
